name: Python Application Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3.12.1
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    # Agregar paso para instalar GeckoDriver
    - name: Install GeckoDriver
      run: |
        wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
        tar -xvzf geckodriver-v0.30.0-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/

    # Ejecutar el test
    - name: Run test
      run: python web/interacting_web_elements.py